spring.application.name=KLTN_GIAPHAONLINE

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/giaphaonline?options=-c%20TimeZone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=root
# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# MinIO
minio.url=http://localhost:9000
minio.public-url=http://localhost:9000
minio.access-key=admin
minio.secret-key=admin123
# Frontend
app.frontend.base-url=http://localhost:5173